### ISSUE TITLE
群消息提示“未知群”

### ISSUE THREAD

**Issue by nmweizi** [Urinx/WeixinBot#10]
[*] 你有新的消息，请注意查收
**未知群** 给你发送了一张图片: img_3456565467.jpg

**Comment by reverland** [comment]
233群没命名吧

**Comment by Urinx** [comment]
默认新建的群聊是没有保存到通讯录的，群名则为成员昵称组合，所以这里通讯录里查不到的一概显示未知

**Comment by sharpdeep** [comment]
群只有加到通讯录才能在getcontact接口获取到，微信网页版能得到一些群的名字是在webwxinit返回数据中ContanctList，我看到的有10个，应该是最近的10个群或者订阅号。

**Comment by reverland** [comment]
@sharpdeep 我记得Urinx是batchgetcontact来获取的，对没有加入通讯录中，或者比如有人刚把你拉到某个群接受到第一条消息时，这种未知群组信息都通过batchgetcontact

**Comment by sharpdeep** [comment]
@reverland 对，我忘了这个接口了，不过在webwxinit也有返回群联系人

**Comment by sbilly** [comment]
fixed in #18
