### ISSUE TITLE
登录超时为什么不轮询呢

### ISSUE THREAD

**Issue by 0x5e** [Urinx/WeixinBot#11]
不轮询的话没几秒程序就退出啦。。
没想到二维码可以这样打印在控制台里，学习了~😁

**Comment by reverland** [comment]
应该保持长连接应该就好，定时检查总觉的很奇怪。。

**Comment by 0x5e** [comment]
@reverland 长连接会超时的。。就几秒钟的样子

**Comment by reverland** [comment]
@0x5e 

超时35000ms，实际上27000ms左右服务器就会返回消息关闭连接。
客户端获取服务端返回的消息就知道是否扫码什么的，作出对应操作。
这时候客户端继续下一次连接，看webweixin 那里似乎是这个逻辑

**Comment by sbilly** [comment]
fixed by #21 and #20 
Thank @mtunique
