### ISSUE TITLE
Mac环境下出现认证失败weixin.py取不到QR code

### ISSUE THREAD

**Issue by Dillettant** [Urinx/WeixinBot#132]
出现错误：

[*] 正在获取 uuid ... 2016-12-05 01:20:14 ******-MacBook-Pro.local root[6783] ERROR URLError = [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
失败

**Comment by movemove** [comment]
When you run the python installer, they display this information to you. It is also documented in /Applications/Python 3.6/ReadMe.rtf, but it's very easily overlooked.

Just browse to Applications/Python 3.6 and double-click Install Certificates.command

**Comment by kongkang** [comment]
thx
