### ISSUE TITLE
关于用户唯一标识

### ISSUE THREAD

**Issue by xuexingdong** [Urinx/WeixinBot#253]
请问网页版的微信是否有能标识是同一个用户的参数，fromUserName在每次网页版微信登陆的时候都会改变

**Comment by chen-junex** [comment]
> 请问网页版的微信是否有能标识是同一个用户的参数，fromUserName在每次网页版微信登陆的时候都会改变

我也遇到这个问题了，请问你找到处理的方法了吗？

**Comment by xuexingdong** [comment]
> > 请问网页版的微信是否有能标识是同一个用户的参数，fromUserName在每次网页版微信登陆的时候都会改变
> 
> 我也遇到这个问题了，请问你找到处理的方法了吗？

没有办法，网页版就是这么设计的，而且很容易被封，我的个人号多年前就已经使用不了网页版了
