### ISSUE TITLE
登录接口失效了？

### ISSUE THREAD

**Issue by zcyc** [Urinx/WeixinBot#265]
今天安装完依赖以后跑demo登录一直都是失败啊。

**Comment by dubyoo** [comment]
我也是，一直提示登录失败：
[INFO] Please use WeChat to scan the QR code .
[INFO] Please confirm to login .
[ERROR] Web WeChat login failed .

**Comment by makelove** [comment]
https://docs.chatie.io/v/zh/

这个稳定
还有iPad版微信破解

**Comment by fikyair** [comment]
> https://docs.chatie.io/v/zh/
> 
> 这个稳定
> 还有iPad版微信破解

求问哪里有iPad版微信破解

**Comment by makelove** [comment]
> > https://docs.chatie.io/v/zh/
> > 这个稳定
> > 还有iPad版微信破解
> 
> 求问哪里有iPad版微信破解

你问官方吧。看文档

**Comment by zcyc** [comment]
> > https://docs.chatie.io/v/zh/
> > 这个稳定
> > 还有iPad版微信破解
> 
> 求问哪里有iPad版微信破解

他那个200块钱一个号一个月

**Comment by WangPney** [comment]
看下这个吧。。。https://wkteam.gitbook.io/api/

**Comment by wbbw007** [comment]
目前有我们有部分API在内测阶段，我们愿意对优秀开发者、企业、学生免费开放一部分内测名额，如果您有意愿请打开下面的地址，填写相关信息，我们会审核您的资质，审核通过后将会根据您留下的联系方式联系您
https://tnwdss67qy.jiandaoyun.com/f/5e6ae0032330170006874524
