### ISSUE TITLE
消息为群组消息时的问题

### ISSUE THREAD

**Issue by stonexer** [Urinx/WeixinBot#3]
line 261:

``` python
elif msg['ToUserName'][:2] == '@@':
    [people, content] = content.split(':<br/>')
    print '|'+name+'| '+people+':\n'+content.replace('<br/>','\n')
```

这里应该是FromUserName吧。来自群组的消息，content是`'id':<br/>'content'`的格式。不知道ToUserName为群组的情况是啥样的。

**Comment by Urinx** [comment]
@stonexer 群消息的ToUserName和FromUserName是一样的，我就随便用了一个，稍后我把不同类型消息的格式的文档补上。: )

**Comment by stonexer** [comment]
OK了
