### ISSUE TITLE
一个奇怪的提示

### ISSUE THREAD

**Issue by hongtu** [Urinx/WeixinBot#30]
[_] 收到疑似红包消息 152 次
[_] 收到疑似红包消息 153 次
[_] 收到疑似红包消息 154 次
[_] 收到疑似红包消息 155 次
[_] 收到疑似红包消息 156 次
[_] 收到疑似红包消息 157 次
[_] 收到疑似红包消息 158 次
[_] 收到疑似红包消息 159 次
[_] 收到疑似红包消息 160 次
[_] 收到疑似红包消息 161 次
[_] 收到疑似红包消息 162 次
[_] 收到疑似红包消息 163 次
[_] 收到疑似红包消息 164 次
[_] 收到疑似红包消息 165 次
[_] 收到疑似红包消息 166 次
[_] 收到疑似红包消息 167 次
[_] 收到疑似红包消息 168 次
[_] 收到疑似红包消息 169 次
[_] 收到疑似红包消息 170 次
[_] 收到疑似红包消息 171 次
[_] 收到疑似红包消息 172 次
[_] 收到疑似红包消息 173 次
[_] 收到疑似红包消息 174 次
[_] 收到疑似红包消息 175 次
[*] 收到疑似红包消息 176 次
……………………一直刷
某次登录后一直刷这个消息，强制结束进程后，重新登陆正常了，这个提示没有了

**Comment by reverland** [comment]
因为synccheck返回

retcode: 0, selector: 6了

然而并不明确这是什么意思，

**Comment by reverland** [comment]
https://github.com/xiangzhai/qwx/blob/master/doc/protocol.md#%E6%9C%89%E6%B6%88%E6%81%AF%E8%BF%94%E5%9B%9E%E7%BB%93%E6%9E%9C

这里说有消息时的返回结果，不确定。

https://github.com/HalfdogStudio/wechat-user-bot/blob/master/doc/webwxApp2aeaf2.js#L2042

webweixin里只是通过selector判断需不需要synccheck，既然web微信都没明确处理，我觉得不需要处理这些意义不是很明确的selector，根据webwxsync结果来处理就好。个人感觉

**Comment by sbilly** [comment]
和 #22 是同一个问题。

@reverland 你贴的意思是说直接忽略即可吗？

**Comment by reverland** [comment]
@sbilly 个人感觉，web微信自身都没明确根据selector来处理，不管它好了

ps: 话说发现webweixin又更新了。。

**Comment by JasLin** [comment]
#22 同一个逻辑
应该是直接忽视即可. 大概这样

``` Javascript
if retcode == '1100':
                print '[*] 你在手机上登出了微信，债见'
                logging.debug('[*] 你在手机上登出了微信，债见')
                break
            if retcode == '1101':
                print '[*] 你在其他地方登录了 WEB 版微信，债见'
                logging.debug('[*] 你在其他地方登录了 WEB 版微信，债见')
                break
            if retcode == '1102':
                print '[*] 你在手机上主动退出了，债见'
                logging.debug('[*] 你在手机上主动退出了，债见')
                break
            elif retcode == '0':
                if selector != '0':
                    r = self.webwxsync()
                    if r is not None:
                        self.handleMsg(r)
                else:
                    time.sleep(1)
            if (time.time() - self.lastCheckTs) <= 20:
                time.sleep(time.time() - self.lastCheckTs)
```

**Comment by Haskely** [comment]
不行啊，一旦出现，selector它一直是6，无法做其他的响应
