### ISSUE TITLE
请大神找下微信朋友圈相关的接口

### ISSUE THREAD

**Issue by FakeMr** [Urinx/WeixinBot#31]
1：获取朋友圈最新消息
2：获取某个好友的朋友圈消息
3：点赞
4：评论

**Comment by 0x5e** [comment]
网页版微信没有相关接口。。

**Comment by reverland** [comment]
。。。要对爬朋友圈感兴趣，可以从流量上入手，或者客户端。。。但好像违反使用协议

**Comment by nehcuoh** [comment]
客户端上的朋友圈信息是https，只有朋友圈图片是明文的吧，而且直接看图片链接，也不知道是谁发的图片。所以朋友圈的接口是加密的，没办法了？

**Comment by reverland** [comment]
@houchen 办法有。。。就像那个抢红包的。。。

**Comment by nehcuoh** [comment]
@reverland 朋友圈红包照片也是你点开照片的时候，会下载原图。这时你是知道这张下载的照片对应哪个人。所以还是没办法是吗

**Comment by reverland** [comment]
@houchen 小米那个自动抢红包实现，好像有点像外挂。我找到再贴链接

**Comment by MatrixMuto** [comment]
现在网页版也是Https了。。

**Comment by sbilly** [comment]
WeixinBot 基于 Web 版，如果 Web 版本没有的功能，就不用考虑了。
