### ISSUE TITLE
请问下 appid 是 什么 的 appid 呢？

### ISSUE THREAD

**Issue by burning-git** [Urinx/WeixinBot#32]
请问下 appid 是 微信开发者 应用的 appid 吗？还是 微信提供的 为 这样呢？
appid ＝ wx782c26e4c19acffb

**Comment by sbilly** [comment]
在哪看到的？

**Comment by burning-git** [comment]
在代码里面！

**Comment by stonexer** [comment]
不太了解，反正 web微信 就用的这个 appid。我想大家都是直接这样用了吧。

**Comment by burning-git** [comment]
有人知道webwxinit 的时候，总是 提示  1101 这是为什么呢？？
 "BaseResponse": {
"Ret": 1101,
"ErrMsg": ""

**Comment by reverland** [comment]
@burning-git 可能你sycnkey错了，或者cookie有问题

**Comment by burning-git** [comment]
sycnkey 是登录之后，返回的吗？？还是 什么时候呢？
