### ISSUE TITLE
打开微信文章的 key 和 登录里的 skey 一样的么？

### ISSUE THREAD

**Issue by iQuick** [Urinx/WeixinBot#33]
弱弱的问大神，在微信里打开信文章时的 key 和 登录里的 skey 一样的么？

**Comment by sbilly** [comment]
你可以在微信里面打开文章自己对比下。

**Comment by iQuick** [comment]
@sbilly 嗯，对比过了，不一样，打开文章时的 key 96 位长，不知道是什么加密方式
