### ISSUE TITLE
支持wx2吗？

### ISSUE THREAD

**Issue by hellokaton** [Urinx/WeixinBot#5]
https://wx2.qq.com 这个接口

**Comment by stonexer** [comment]
只是一个sync接口的区别吧，改一下应该就没问题了

**Comment by hellokaton** [comment]
新的登陆在返回跳转url的时候变成wx2.qq.com了，我试试先

**Comment by stonexer** [comment]
可以试下把webpush的改成webpush2

**Comment by hellokaton** [comment]
![desctop screenshot](https://cloud.githubusercontent.com/assets/3849072/12886520/ed0f89b6-cea8-11e5-9dc6-e0770f518895.png)
什么鬼

**Comment by hellokaton** [comment]
`获取联系人 ...`
这一步不往下走了

**Comment by stonexer** [comment]
@biezhi https://github.com/stonexer/WeixinBot 试下这个呢

**Comment by hellokaton** [comment]
@stonexer 还是在获取联系人那儿卡住了，你的可以吗？

**Comment by hellokaton** [comment]
https://github.com/stonexer/WeixinBot 这个项目的ISSUES没开启

**Comment by stonexer** [comment]
看图上不是走到了进行同步线路测试么

**Comment by Urinx** [comment]
@biezhi 图上的问题好诡异，如果获取联系人失败了，咋没退出，还继续走了下面的流程。。 :joy:

**Comment by hellokaton** [comment]
@Urinx  我按了回车的，python的问题我没找到。。。不过用java实现了，抓包分析了一下。
