### ISSUE TITLE
windows下print时字符集原因，print都是乱码

### ISSUE THREAD

**Issue by nmweizi** [Urinx/WeixinBot#9]
windows下print时字符集原因，print都是乱码

**Comment by sbilly** [comment]
这个还存在吗？

**Comment by mtunique** [comment]
用UnicodeStreamFilter  dirty fix了， 但是现在和colorama不兼容

**Comment by sbilly** [comment]
这个 pull request 还是没有修复吧？

**Comment by mtunique** [comment]
@sbilly 恩 stderr 也用下 UnicodeStreamFilter 就好了

**Comment by mtunique** [comment]
新的 commit 加进去了
