### ISSUE TITLE
我是小白  File "weixin.py", line 1080, in <module>     import coloredlogs ImportError: No module named coloredlogs

### ISSUE THREAD

**Issue by xiaobai-little** [Urinx/WeixinBot#91]
D:\WeixinBot-master>python weixin.py
Traceback (most recent call last):
  File "weixin.py", line 1080, in <module>
    import coloredlogs
ImportError: No module named coloredlogs

win10系统 Python2.7，已装qrcode，运行不了，求老司机带~

**Comment by KleinYuan** [comment]
意思就是你没coloredlogs mdule 咯。
`pip install coloredlogs`
repo里有个requirements文件，
`
colorama
coloredlogs
humanfriendly
lxml
qrcode
requests
six
requests_toolbelt`

`pip install -r ${Path}/requirements.txt`
把Path变成你这个repo的path
然后check下你python的版本，python2.7.5 会有EOF505 error. 用Python2.7.12 就ok了
